package testutil

import (
	"os"
	"time"

	"easy-orders-backend/internal/config"
	"easy-orders-backend/internal/models"
	"easy-orders-backend/pkg/database"
	"easy-orders-backend/pkg/logger"

	"github.com/google/uuid"
	"go.uber.org/zap"
)

// CreateTestUser creates a test user with default values
func CreateTestUser(overrides ...func(*models.User)) *models.User {
	user := &models.User{
		ID:        uuid.New().String(),
		Name:      "Test User",
		Email:     "test@example.com",
		Password:  "$2a$10$test.hash",
		Role:      models.UserRoleCustomer,
		IsActive:  true,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	for _, override := range overrides {
		if override != nil {
			override(user)
		}
	}

	return user
}

// CreateTestProduct creates a test product with default values
func CreateTestProduct(overrides ...func(*models.Product)) *models.Product {
	product := &models.Product{
		ID:          uuid.New().String(),
		Name:        "Test Product",
		Description: "Test Description",
		SKU:         "TEST-SKU-" + uuid.New().String()[:8],
		Price:       99.99,
		IsActive:    true,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}

	for _, override := range overrides {
		if override != nil {
			override(product)
		}
	}

	return product
}

// CreateTestInventory creates a test inventory with default values
func CreateTestInventory(productID string, overrides ...func(*models.Inventory)) *models.Inventory {
	inventory := &models.Inventory{
		// ID is auto-generated by database, don't set it
		ProductID: productID,
		Quantity:  100,
		Reserved:  0,
		Available: 100,
		MinStock:  10,
		MaxStock:  1000,
		Version:   1,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	for _, override := range overrides {
		if override != nil {
			override(inventory)
		}
	}

	return inventory
}

// CreateTestOrder creates a test order with default values
func CreateTestOrder(userID string, overrides ...func(*models.Order)) *models.Order {
	order := &models.Order{
		ID:          uuid.New().String(),
		UserID:      userID,
		Status:      models.OrderStatusPending,
		TotalAmount: 199.99,
		Currency:    "USD",
		Notes:       "Test order",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}

	for _, override := range overrides {
		if override != nil {
			override(order)
		}
	}

	return order
}

// CreateTestOrderItem creates a test order item with default values
func CreateTestOrderItem(orderID, productID string, overrides ...func(*models.OrderItem)) *models.OrderItem {
	item := &models.OrderItem{
		ID:         uuid.New().String(),
		OrderID:    orderID,
		ProductID:  productID,
		Quantity:   2,
		UnitPrice:  99.99,
		TotalPrice: 199.98,
		CreatedAt:  time.Now(),
		UpdatedAt:  time.Now(),
	}

	for _, override := range overrides {
		if override != nil {
			override(item)
		}
	}

	return item
}

// CreateTestPayment creates a test payment with default values
func CreateTestPayment(orderID string, overrides ...func(*models.Payment)) *models.Payment {
	payment := &models.Payment{
		ID:            uuid.New().String(),
		OrderID:       orderID,
		Amount:        199.99,
		Method:        models.PaymentMethodCreditCard,
		Status:        models.PaymentStatusPending,
		TransactionID: "TXN-" + uuid.New().String()[:8],
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
	}

	for _, override := range overrides {
		if override != nil {
			override(payment)
		}
	}

	return payment
}

// CreateTestNotification creates a test notification with default values
func CreateTestNotification(userID string, overrides ...func(*models.Notification)) *models.Notification {
	notification := &models.Notification{
		ID:        uuid.New().String(),
		UserID:    userID,
		Type:      models.NotificationTypeOrderConfirmed,
		Title:     "Test Notification",
		Body:      "Test message body",
		Channel:   models.NotificationChannelInApp,
		Read:      false,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	for _, override := range overrides {
		if override != nil {
			override(notification)
		}
	}

	return notification
}

// Float64Ptr returns a pointer to a float64 value
func Float64Ptr(v float64) *float64 {
	return &v
}

// IntPtr returns a pointer to an int value
func IntPtr(v int) *int {
	return &v
}

// StringPtr returns a pointer to a string value
func StringPtr(v string) *string {
	return &v
}

// TimePtr returns a pointer to a time value
func TimePtr(v time.Time) *time.Time {
	return &v
}

// SetupTestDatabase creates a connection to the test database
func SetupTestDatabase() (*database.DB, error) {
	// Use environment variables from docker-compose
	// Inside container: postgres:5432
	dbConfig := &config.DatabaseConfig{
		Host:     getEnv("DB_HOST", "postgres"),
		Port:     getEnv("DB_PORT", "5432"),
		User:     getEnv("DB_USER", "postgres"),
		Password: getEnv("DB_PASSWORD", "postgres"),
		DBName:   getEnv("DB_NAME", "easy_orders"),
		SSLMode:  getEnv("DB_SSLMODE", "disable"),
		MaxConns: 25,
		MaxIdle:  5,
	}

	return database.New(dbConfig)
}

// TeardownTestDatabase closes the database connection
func TeardownTestDatabase(db *database.DB) {
	if db != nil {
		_ = db.Close()
	}
}

// RunMigrations runs all database migrations
func RunMigrations(db *database.DB) error {
	// Auto-migrate all models
	return db.AutoMigrate(
		&models.User{},
		&models.Product{},
		&models.Inventory{},
		&models.Order{},
		&models.OrderItem{},
		&models.Payment{},
		&models.Notification{},
		&models.AuditLog{},
	)
}

// CleanDatabase truncates all tables for a clean test state
func CleanDatabase(db *database.DB) {
	// Delete in reverse order to respect foreign key constraints
	db.Exec("TRUNCATE TABLE audit_logs CASCADE")
	db.Exec("TRUNCATE TABLE notifications CASCADE")
	db.Exec("TRUNCATE TABLE payments CASCADE")
	db.Exec("TRUNCATE TABLE order_items CASCADE")
	db.Exec("TRUNCATE TABLE orders CASCADE")
	db.Exec("TRUNCATE TABLE inventory CASCADE")
	db.Exec("TRUNCATE TABLE products CASCADE")
	db.Exec("TRUNCATE TABLE users CASCADE")
}

// NewTestLogger creates a no-op logger for testing
func NewTestLogger() *logger.Logger {
	zapLogger, _ := zap.NewDevelopment()
	return &logger.Logger{
		SugaredLogger: zapLogger.Sugar(),
	}
}

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}
