package services

import (
	"context"
	"errors"

	"easy-orders-backend/internal/models"
	"easy-orders-backend/internal/repository"
	"easy-orders-backend/pkg/logger"
)

// userService implements UserService interface
type userService struct {
	userRepo repository.UserRepository
	logger   *logger.Logger
}

// NewUserService creates a new user service
func NewUserService(userRepo repository.UserRepository, logger *logger.Logger) UserService {
	return &userService{
		userRepo: userRepo,
		logger:   logger,
	}
}

func (s *userService) CreateUser(ctx context.Context, req CreateUserRequest) (*UserResponse, error) {
	s.logger.Info("Creating user", "email", req.Email)

	// TODO: Validate request
	// TODO: Hash password
	// TODO: Check if user already exists

	user := &models.User{
		Email: req.Email,
		Name:  req.Name,
		Role:  models.UserRoleCustomer, // Default role
		// ID will be generated by repository
	}

	if err := s.userRepo.Create(ctx, user); err != nil {
		s.logger.Error("Failed to create user", "error", err, "email", req.Email)
		return nil, err
	}

	s.logger.Info("User created successfully", "id", user.ID, "email", req.Email)

	return &UserResponse{
		ID:    user.ID,
		Email: user.Email,
		Name:  user.Name,
	}, nil
}

func (s *userService) GetUser(ctx context.Context, id string) (*UserResponse, error) {
	s.logger.Debug("Getting user", "id", id)

	user, err := s.userRepo.GetByID(ctx, id)
	if err != nil {
		s.logger.Error("Failed to get user", "error", err, "id", id)
		return nil, err
	}

	return &UserResponse{
		ID:    user.ID,
		Email: user.Email,
		Name:  user.Name,
	}, nil
}

func (s *userService) UpdateUser(ctx context.Context, id string, req UpdateUserRequest) (*UserResponse, error) {
	s.logger.Info("Updating user", "id", id)

	// Get existing user
	user, err := s.userRepo.GetByID(ctx, id)
	if err != nil {
		s.logger.Error("Failed to get user for update", "error", err, "id", id)
		return nil, err
	}

	// Update fields if provided
	if req.Name != nil {
		user.Name = *req.Name
	}
	if req.Email != nil {
		user.Email = *req.Email
	}

	if err := s.userRepo.Update(ctx, user); err != nil {
		s.logger.Error("Failed to update user", "error", err, "id", id)
		return nil, err
	}

	s.logger.Info("User updated successfully", "id", id)

	return &UserResponse{
		ID:    user.ID,
		Email: user.Email,
		Name:  user.Name,
	}, nil
}

func (s *userService) DeleteUser(ctx context.Context, id string) error {
	s.logger.Info("Deleting user", "id", id)

	if err := s.userRepo.Delete(ctx, id); err != nil {
		s.logger.Error("Failed to delete user", "error", err, "id", id)
		return err
	}

	s.logger.Info("User deleted successfully", "id", id)
	return nil
}

func (s *userService) ListUsers(ctx context.Context, req ListUsersRequest) (*ListUsersResponse, error) {
	s.logger.Debug("Listing users", "offset", req.Offset, "limit", req.Limit)

	users, err := s.userRepo.List(ctx, req.Offset, req.Limit)
	if err != nil {
		s.logger.Error("Failed to list users", "error", err)
		return nil, err
	}

	userResponses := make([]UserResponse, len(users))
	for i, user := range users {
		userResponses[i] = UserResponse{
			ID:    user.ID,
			Email: user.Email,
			Name:  user.Name,
		}
	}

	return &ListUsersResponse{
		Users: userResponses,
		Total: len(userResponses), // TODO: Get actual total count
	}, nil
}

func (s *userService) AuthenticateUser(ctx context.Context, email, password string) (*AuthResponse, error) {
	s.logger.Debug("Authenticating user", "email", email)

	// TODO: Implement proper authentication
	// - Get user by email
	// - Verify password hash
	// - Generate JWT token

	user, err := s.userRepo.GetByEmail(ctx, email)
	if err != nil {
		s.logger.Error("Failed to get user for authentication", "error", err, "email", email)
		return nil, errors.New("invalid credentials")
	}

	// TODO: Verify password
	// For now, just return a placeholder response
	return &AuthResponse{
		Token: "placeholder-jwt-token",
		User: UserResponse{
			ID:    user.ID,
			Email: user.Email,
			Name:  user.Name,
		},
	}, nil
}
